name: CI Check + Auto Deploy

on:
  push:
    branches: [main]

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout karo
        uses: actions/checkout@v4

      - name: Node.js setup karo
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Dependencies install karo
        run: npm install

      - name: Build check karo
        run: npm run build --if-present

      - name: Check karo sab files hain
        run: |
          echo "✅ Dependencies installed!"
          echo "📁 Project files:"
          ls -la public/s